[project]
name = "synopsis-mkdocs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "livereload>=2.7.1",
    "mkdocs>=1.6.1",
    "mkdocs-dracula-theme>=1.0.8",
    "mkdocs-material>=9.7.0",
]
